### ISSUE TITLE
Apiloc is missing from /src

### ISSUE THREAD

**Issue by AdityaBahl** [RGTechno/CourierTnM#1]
Hi, Kindly look into apiloc being missing from the src folder.

**Comment by RGTechno** [comment]
Hey!
Added the following in the latest commit.
Thanks

**Comment by AdityaBahl** [comment]
Hi, can you please provide me with any social media or email of yours, I have some doubts, and really love your project and hard work in this.

**Comment by RGTechno** [comment]
Hey @AdityaBahl you can reach out to me on LinkedIn (https://www.linkedin.com/in/rgtechno/)

**Comment by AdityaBahl** [comment]
Hey, I have dropped a message, kindly check it out whenever free.
